-- This migration was intended to convert INT columns to BIGINT using BIGSERIAL,
-- but BIGSERIAL is not valid in ALTER COLUMN SET DATA TYPE statements in PostgreSQL.
-- The migration was marked as applied but never actually changed the column types.
-- The schema remains using Int (@default(autoincrement())) which matches the actual DB state.
-- No-op migration kept for migration history integrity.
